// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2026 Ambiq

import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';

const NOTICES_FILE = 'THIRD-PARTY-NOTICES.md';

/**
 * Emits the committed third-party notices file into the build output so the
 * deployed site serves it alongside the app. The file is generated by
 * `npm run notices`; the build fails if it is missing, so the deploy can never
 * silently ship without notices.
 */
function thirdPartyNotices(): Plugin {
  return {
    name: 'tileio:third-party-notices',
    apply: 'build',
    generateBundle() {
      const source = path.resolve(__dirname, NOTICES_FILE);
      let contents: string;
      try {
        contents = readFileSync(source, 'utf8');
      } catch {
        throw new Error(
          `${NOTICES_FILE} is missing. Run \`npm run notices\` and commit the result.`
        );
      }
      this.emitFile({ type: 'asset', fileName: NOTICES_FILE, source: contents });
    },
  };
}

/** Short commit of the build. See #31 */
function buildCommit(): string {
  // The Pages checkout is shallow and detached, so prefer what the runner already knows.
  const sha = process.env.GITHUB_SHA;
  if (sha) {
    return sha.slice(0, 7);
  }
  try {
    return execFileSync('git', ['rev-parse', '--short', 'HEAD'], {
      cwd: __dirname,
      stdio: ['ignore', 'pipe', 'ignore'],
    }).toString().trim();
  } catch {
    return 'dev';
  }
}

function appVersion(): string {
  const pkg = JSON.parse(readFileSync(path.resolve(__dirname, 'package.json'), 'utf8'));
  return pkg.version as string;
}

export default defineConfig(() => {
  const APP_BASE_URL = process.env.APP_BASE_URL || '/';
  console.log('APP_BASE_URL', APP_BASE_URL);
  return {
    base: APP_BASE_URL,
    define: {
      __APP_VERSION__: JSON.stringify(appVersion()),
      __APP_COMMIT__: JSON.stringify(buildCommit()),
    },
    build: {
      outDir: 'build',
    },
    plugins: [thirdPartyNotices()],
    // plugins: [react(), thirdPartyNotices()],
  };
});
