// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2026 Ambiq

import { readFileSync } from 'node:fs';
import path from 'node:path';
import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';

const NOTICES_FILE = 'THIRD-PARTY-NOTICES.md';

/**
 * Emits the committed third-party notices file into the build output so the
 * deployed site serves it alongside the app. The file is generated by
 * `npm run notices`; the build fails if it is missing, so the deploy can never
 * silently ship without notices.
 */
function thirdPartyNotices(): Plugin {
  return {
    name: 'tileio:third-party-notices',
    apply: 'build',
    generateBundle() {
      const source = path.resolve(__dirname, NOTICES_FILE);
      let contents: string;
      try {
        contents = readFileSync(source, 'utf8');
      } catch {
        throw new Error(
          `${NOTICES_FILE} is missing. Run \`npm run notices\` and commit the result.`
        );
      }
      this.emitFile({ type: 'asset', fileName: NOTICES_FILE, source: contents });
    },
  };
}

export default defineConfig(() => {
  const APP_BASE_URL = process.env.APP_BASE_URL || '/';
  console.log('APP_BASE_URL', APP_BASE_URL);
  return {
    base: APP_BASE_URL,
    build: {
      outDir: 'build',
    },
    plugins: [thirdPartyNotices()],
    // plugins: [react(), thirdPartyNotices()],
  };
});
